In [1]:
# 배열 간 연산
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


In [2]:
# 배열과 스칼라 연산
arr = np.array([1,2,3])
print(arr + 10)
print(arr * 2)

[11 12 13]
[2 4 6]


In [26]:
# 배열 연산 - 브로드캐스팅
arr2d = np.array([[1,2,3],
                  [4,5,6]])
arr1d = np.array([10,20,30])
print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


In [27]:
A = np.array([[1],
              [2],
              [3]])
B = np.array([10,20,30])
print((A+B))

[[11 21 31]
 [12 22 32]
 [13 23 33]]


##### 실습1. 배열 연산(1)
###### 다음 배열을 생성하고, 모든 요소에 3을 더함

In [5]:
arr = np.array([1,2,3,4])
print(arr*3)

[ 3  6  9 12]


###### 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열

In [8]:
arr = np.array([[5,10],
                [15,20]])
ar = arr*-1
print(ar)

[[ -5 -10]
 [-15 -20]]


###### 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 출력

In [15]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,2,3])
print(arr1 * arr2)
print(arr1 / arr2)

[ 2  8 18]
[2. 2. 2.]


###### 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 필요한 값을 더한 결과 배열을 브로드 캐스팅으로 만들기

In [ ]:
arr = np.array([[95,97],
                [80,85]])

print((100 - arr) + arr)


[[100 100]
 [100 100]]


###### 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열(브로드캐스팅 이용)

In [30]:
arr = np.array([[1,2,3],
                [4,5,6]])
ar = [[10],
      [100]]
print(arr*ar)


[[ 10  20  30]
 [400 500 600]]


##### 아래 배열에서 각 행마다 다른 스칼라 값을 더하기
###### 1차원 배열을 만들어 브로드 캐스팅 연산을 수행
###### 첫 번째 행에 100, 두 번째 행에 200, 세 번째 행에 300

In [38]:
arr = np.array([[10,20],
                [30,40],
                [50,60]])
ar1 =[100]
ar2 = [200]
ar3 = [300]
ar = list(zip(ar1,ar2,ar3))
ar0 = np.array(ar)
print(arr*ar0.T)

[[ 1000  2000]
 [ 6000  8000]
 [15000 18000]]


##### 통계 함수 및 집계 연산

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(np.sum(arr))  # 합계
print(np.mean(arr)) # 평균
print(np.std(arr))  # 표준 편차
print(np.min(arr))  # 최솟값
print(np.max(arr))  # 최댓값

21
3.5
1.707825127659933
1
6


In [41]:
arr = np.array([10,3,25,7])

min_index = np.argmin(arr)
max_index = np.argmax(arr)
print("최솟값 인덱스:",min_index)   # 배열에서 최솟값이 있는 인덱스를 반환
print("최댓값 인덱스:",max_index)   # 배열에서 최댓값이 있는 인덱스를 반환

최솟값 인덱스: 1
최댓값 인덱스: 2


In [42]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(np.sum(arr, axis=0))  # 열병 합 [5,7,9]
print(np.sum(arr, axis=1))  # 행병 합 [ 6 15]

[5 7 9]
[ 6 15]


In [ ]:
arr = np.array([1,2,3,4])
print(np.cumsum(arr))   # 누적 합
print(np.cumprod(arr))  # 누적 곱 

[ 1  3  6 10]
[ 1  2  6 24]


##### 실습2. 통계 함수 및 집계 연산(1)
###### 아래 배열의 전체 합계와 평균

In [44]:
arr = np.array([5,10,15,20])
print("배열의 전체 합계:",np.sum(arr))
print("배열의 평균:",np.mean(arr))

배열의 전체 합계: 50
배열의 평균: 12.5


###### 다음 2차원 배열에서 전체 최솟값과 최댓값

In [46]:
arr = np.array([[3,7,1],
               [9,2,8]])
print("배열의 최솟값:",np.min(arr))
print("배열의 최댓값:",np.max(arr))

배열의 최솟값: 1
배열의 최댓값: 9


###### 아래 배열에서 각 열의 합계와 각 행의 합계를 구하기

In [57]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("행별 합계:",np.sum(arr,axis=1))
print("열별 합계:",np.sum(arr,axis=0))

행별 합계: [ 6 15 24]
열별 합계: [12 15 18]


##### 실습2. 통계 함수 및 집계 연산(2)
###### 아래 배열에서 행별 평균과 열별 평균을 각각 구하기

In [56]:
arr = np.array([[10,20],
                [30,40],
                [50,60]])
print("행별 평균:",np.mean(arr,axis=1))
print("열별 평균:",np.mean(arr,axis=0))

행별 평균: [15. 35. 55.]
열별 평균: [30. 40.]


###### 1차원 배열에서 전체 표준편차를 구하고, 각 요소가 평균으로부터 얼마나 떨어져 있는지 편차 배열(값 - 평균)

In [52]:
arr = np.array([2,4,4,4,5,5,7,9])
print("전체 표준편차:",np.std(arr))
print("편차 배열:",arr-np.mean(arr))

전체 표준편차: 2.0
편차 배열: [-3. -1. -1. -1.  0.  0.  2.  4.]


###### 아래 2차원 배열에서 행 단위 누적 합과 열 단위 누적 곱

In [54]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("행 단위 누적 합:",np.cumsum(arr,axis=1))
print("열 단위 누적 곱:",np.cumprod(arr,axis=0))

행 단위 누적 합: [[ 1  3  6]
 [ 4  9 15]]
열 단위 누적 곱: [[ 1  2  3]
 [ 4 10 18]]


In [59]:
# 조건 기반 선택 함수
import numpy as np
arr = np.array([10,20,30,40,50])
result = np.where(arr > 30, "High","Low")
print(result)

['Low' 'Low' 'Low' 'High' 'High']


In [ ]:
arr = np.array([10,20,30,40,50])
indices = np.where(arr > 30)
print(indices)  # (array([3,4]),)
print(arr[indices]) # [40 50]

(array([3, 4]),)
[40 50]


In [ ]:
arr = np.array([10,20,30,40,50])
# AND: 20 < x < 50
mask_and = (arr > 20) & (arr < 50)
print(mask_and) # [False False  True  True False]
print(arr[mask_and])    # [30 40]

[False False  True  True False]
[30 40]


In [ ]:
arr = np.array([10,20,30,40,50])
# OR: x < 20 or x > 40
mask_or = (arr < 20) | (arr > 40)
print(mask_or)  # [ True False False False  True]
print(arr[mask_or]) # [10 50]

[ True False False False  True]
[10 50]


In [64]:
arr = np.array([10,20,30,40,50])
# NOT: 조건 부정
mask_not = ~(arr > 30)
print(arr[mask_not])    # [10 20 30]

[10 20 30]


In [ ]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
mask = (arr2d % 2 == 0) | (arr2d > 7)
print(mask)
# [[False  True False]
#  [ True False  True]
#  [False  True  True]]
print(arr2d[mask])  # [2 4 6 8 9]

[[False  True False]
 [ True False  True]
 [False  True  True]]
[2 4 6 8 9]


##### 실습3.논리 연산과 조건 연산(1)
###### 1차원 배열 [5,12,18,7,30,25]에서 10 보다 크고 20보다 작은 값만 필터링

In [66]:
arr = np.array([5,12,18,7,30,25])
mask_and = (arr>10) & (arr<20)
print(arr[mask_and])

[12 18]


###### 배열 [10,15,20,25,30,35]에서 15 이하이거나 30 이상인 값만 선택

In [67]:
arr = np.array([10,15,20,25,30,35])
mask_or = (arr <= 15) | (arr >= 30)
print(arr[mask_or])

[10 15 30 35]


###### 배열 [3,8,15,6,2,20]에서 10 이상인 값을 모두 0으로 변경

In [68]:
arr = np.array([3,8,15,6,2,20])
mask_not = ~(arr>=10)
print(arr[mask_not])

[3 8 6 2]


###### 배열 [7,14,21,28,35]에서 20 이상인 값은 "High",나머지는 "Low"로 표시

In [70]:
arr = np.array([7,14,21,28,35])
indices = np.where(arr > 20,"High","Low")
print(indices)

['Low' 'Low' 'High' 'High' 'High']


##### 실습3. 논리 연산과 조건 연산(2)
###### 0~9 범위의 배열에서 짝수는 그대로 두고, 홀수는 홀수 값 x 10으로 변환한 배열