In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)

(2, 3)
2


In [3]:
arr = np.array([1,2,3])
print(arr.dtype)

float_arr = np.array([1.0,2.0])
print(float_arr.dtype)

int64
float64


In [4]:
arr = np.array([1,2,3])
float_arr = arr.astype(np.float32)
print(float_arr.dtype)

float32


In [7]:
print(np.zeros((2,3))) # 2행 3열 모두 0.0
print(np.ones((3,2)))  # 3행 2열 모두 1
print(np.empty((2,2))) # 값이 초기화되지 않음
print(np.full((2,2),7))    # [[7 7]
                           #  [7 7]]
print(np.eye(3))    # n x n 단위행렬
print(np.eye(3,5,k=1)) # 3 x 5 행렬에서 k=1인 대각행렬

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [11]:
print(np.arange(0,10,2))    # 0 이상 10 미만의 정수 배열을 2간격
print(np.linspace(0,1,5))   # 0 부터 1까지의 균일 간격으로 5개 요소의 배열

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [54]:
print(np.random.rand(2,2))  # 2 x 2 크기의 배열 난수로 생성 (0~1사이의 난수)
print(np.random.randn(2,2)) # 2 x 2 크기의 정규분포를 따르는 난수 생성(평균:0 분산:1)
print(np.random.randint(0,10,(2,3)))    # 0~9 사이 정수 2x3 배열
np.random.seed(49)  # 시드 설정
print(np.random.rand(3))    # 항상 동일한 결과


[[0.89160344 0.68327676]
 [0.56688466 0.54696588]]
[[ 0.65918479 -0.70762202]
 [ 0.30328987  0.54217157]]
[[1 6 4]
 [8 3 8]]
[0.30096446 0.24706183 0.92633514]


In [55]:
from numpy.random import default_rng

rng = default_rng(seed=42)  # rng 객체 생성
print(rng.integers(1,10,size=5))    # 정수 난수
print(rng.random(3))    # 실수 난수
print(rng.normal(0,1,size=(2,3)))   # 정규분포
print(rng.uniform(5,10,size=3)) # 균등분포

[1 7 6 4 4]
[0.69736803 0.09417735 0.97562235]
[[ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]]
[8.2193256  9.11380807 7.21707099]


##### 실습1. 배열 초기화 및 생성(1)
###### 0으로 채워진 크기(3,4) 배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열

In [64]:
a = np.zeros((3,4),dtype=int)
a +=5
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


###### 0부터 20까지 2씩 증가하는 1차원 배열을 생성

In [63]:
arr = np.arange(0,22,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


###### 0~1 사이의 실수 난수를 가지는 (2,3) 크기의 배열

In [74]:
arr = np.random.rand(2,3)
print(arr)

[[0.83122673 0.01016757 0.68510556]
 [0.13707157 0.92864891 0.62176241]]


###### 평균이 100, 표준편차가 20인 정규분포 난수 6개

In [84]:
from numpy.random import default_rng
rng = default_rng()
print(rng.normal(100,20,6))

[74.44978634 80.9001223  91.44341217 82.16232717 93.25362146 79.3212459 ]


###### 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4,5) 크기의 2차원 배열로 변환

In [89]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


###### 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성, 이를 (3,4) 크기로 변환

In [90]:
arr = np.linspace(0,1,12).reshape(3,4)
print(arr)

[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


###### 0~99 사이의 난수로 이루어진 (10,10) 배열을 생성한 뒤, np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열

In [96]:
arr = np.random.randint(0,100,(10,10))
arr1 = np.eye(10,dtype=int)
print(arr+arr1)

[[ 85  83  63  72  90  98  14  24  38  11]
 [  0  50  49  66  78  21  72  73  17  16]
 [ 61  71  98   8  27  33  93   9  92  45]
 [ 16  34  14   6  28  64  76   0  74  14]
 [ 39  43   3  87   7  22  88  29  61  50]
 [ 86  54  95  30   0  24  98  10  88  65]
 [ 69  67  30  38  80  39  78  82  86  61]
 [ 82  90  75  93  98  58  32  92  24  82]
 [ 47  92  55  65  73  34   6  46  50  33]
 [ 67  61   1  25  55  87  21  41  42 100]]


###### 0 ~ 9 사이의 난수로 이루어진 (2,3,4) 3차원 배열

In [100]:
arr = np.random.randint(0,10,(2,3,4))
print(arr)

[[[0 5 4 4]
  [4 2 6 1]
  [9 7 9 6]]

 [[2 3 9 4]
  [5 0 4 3]
  [0 7 8 1]]]


##### 실습2. 인덱싱과 슬라이싱(1)
###### 다음 배열에서 2,4,6번째 요소를 Fancy Indexing으로 선택

In [101]:
arr = np.arange(10,30,2)
arr = arr[[1,3,5]]
print(arr)

[12 16 20]


###### 3x3 배열에서 왼쪽 위 -> 오른쪽 아래 대각선의 요소만 인덱싱

In [105]:
arr = np.arange(1,10).reshape(3,3)
print(np.diag(arr))

[1 5 9]


###### 3x4 배열에서 마지막 열만 선택해 모두 -1로 변경

In [106]:
arr = np.arange(1,13).reshape(3,4)
arr[:,-1] = -1
print(arr)

[[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]


###### 4x4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력

In [7]:
arr = np.arange(1,17).reshape(4,4)
print(arr[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


##### 실습2. 인덱싱과 슬라이싱(2)
###### 4x5 배열에서 가운데 2x3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열

In [12]:
arr = np.arange(1,21).reshape(4,5)
arr1 = arr[1:3,1:4].copy()
print(arr)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]]


###### 3x4 배열에서 짝수이면서 10 이상인 값만 선택(& 활용)

In [17]:
arr = np.array([[4,9,12,7],[10,15,18,3],[2,14,6,20]])
print(arr[(arr >= 10) & (arr%2==0)])

[12 10 18 14 20]


###### 5x5 배열에서 2,4번째 행을 선택, 선택된 행에서 열 순서를 [4,0,2]로 재배치

In [56]:
arr = np.arange(1,26).reshape(5,5)
row = [1,3]
col = [4,0,2]
arr1 = arr[row,:]
arr2 = arr1[:,col]
print(arr2)

[[10  6  8]
 [20 16 18]]


##### 실습2. 인덱싱과 슬라이싱(3)
###### 5x3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택

In [35]:
arr = np.array([[10,20,30],[55,65,75],[40,45,50],[70,80,90],[15,25,35]])
mask = arr[:,0] >= 50
print(mask)
print(arr[mask])

[False  True False  True False]
[[55 65 75]
 [70 80 90]]


###### 4x4 배열에서 (0,1),(1,3),(2,0),(3,2) 위치의 요소를 한 번에 선택

In [48]:
arr = np.arange(1,17).reshape(4,4)
row = [0,1,2,3]
col = [1,3,0,2]
print(arr[row,col])

[ 2  8  9 15]


###### 3차원 배열(2,3,4)에서 모든 블록에서 두 번째 열만 추출해 새로운 2차원 배열 (2,3)을 생성

In [76]:
arr3d = np.arange(24).reshape(2,3,4)
print(arr3d[:,:,1])


[[ 1  5  9]
 [13 17 21]]


##### 실습3. NumPy 종합 연습(1)
###### 0부터 24까지 정수를 가진 배열을 만들고, (5,5) 배열로 변환한 뒤 가운데 행(3번째 행)과 가운데 열(3번째 열)을 각각 1차원 배열로 출력

In [81]:
arr = np.arange(25).reshape(5,5)
print("가운데 행:",arr[2,:])
print("가운데 열:",arr[:,2])

가운데 행: [10 11 12 13 14]
가운데 열: [ 2  7 12 17 22]


###### 0~99 난수로 이루어진(10,10)배열을 생성, 짝수 인덱스의 행만 출력

In [102]:
arr = np.random.randint(0,100,(10,10))
print(arr[::2])

[[86  5 96 41 53 94 63 17  8 55]
 [ 3 68 28 37 46 53 31 21 82 33]
 [88 86 89 60 19 16 21 41  7 18]
 [51 49  1 18 53 14 36  3 13 19]
 [45 60 74 10 21 48 70 80  1 17]]


###### 0부터 49까지 정수를 가진 배열을 (5,10) 배열로 변환한 후, 2행 3열부터 4행 7열까지의 부분 배열을 추출

In [106]:
arr = np.arange(50).reshape(5,10)
print(arr[1:4,2:8])

[[12 13 14 15 16 17]
 [22 23 24 25 26 27]
 [32 33 34 35 36 37]]


###### 0~9 난수로 이루어진(4,4)배열을 생성하고, 각각 인덱싱으로 추출(for 이용)

In [150]:
arr = np.random.randint(0,10,(4,4))
print(arr)
print("주대각선 요소:",np.diag(arr))
print("부대각선 요소:",np.diag(np.fliplr(arr)))

[[8 5 1 4]
 [7 5 5 9]
 [8 3 8 8]
 [6 1 9 9]]
주대각선 요소: [8 5 8 9]
부대각선 요소: [4 5 3 6]


###### 0~9 난수로 이루어진 (3,4,5) 3차원 배열을 생성하고, 두 번째 층에서 첫 번째 항과 마지막 열을 값을 출력

In [155]:
arr = np.random.randint(0,10,(3,4,5))
print(arr)
print("두 번째 중의 첫 행 마지막 열 값:",arr[1,0,4])

[[[1 4 1 6 3]
  [0 7 0 2 9]
  [5 4 6 8 7]
  [3 4 1 4 5]]

 [[6 2 3 2 5]
  [1 6 2 6 4]
  [4 5 4 9 4]
  [9 5 1 9 1]]

 [[9 2 9 5 9]
  [9 7 7 6 5]
  [9 7 4 9 4]
  [9 6 8 6 1]]]
두 번째 중의 첫 행 마지막 열 값: 5


##### 실습3. NumPy 종합 연습(3)
###### 35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10x4 행렬로 변환 후 출력

In [156]:
arr = np.arange(35,75).reshape(10,4)
print(arr)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


###### 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력

In [ ]:
arr = np.arange(35,75).reshape(10,4)
print(arr[::-1])

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


###### 6번에서 만든 배열 중 두 번째 행부터 마지막 직전 행까지, 세번째 열부터 마지막 열까지 슬라이싱해서 출력

In [169]:
arr = np.arange(35,75).reshape(10,4)
print(arr[1:-1,2:])

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


##### 실습3. NumPy 종합 연습(4)
###### 1부터 50까지의 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력

In [176]:
arr = np.random.randint(1,51,(5,6))
print(arr[arr%2==0])

[14 44 44 30 50 28 42 26 48 12  8 42 24 36 16 42]


###### 0부터 99까지의 정수로 이루어진 (10,10) 배열을 생성한 후, [1,3,5]번째 항과 [2,4,6]번째 열의 교차하는 원소들만 선택하여 출력

In [182]:
arr = np.arange(100).reshape(10,10)
row = [1,3,5]
col = [2,4,6]
arr1 = arr[row,:]
arr2 = arr1[:,col]
print(arr2)

[[12 14 16]
 [32 34 36]
 [52 54 56]]


###### 0~9난수로 이루어진 1차원 배열(길이15)을 생성하고, 짝수 인덱스 위치에 있는 값들 중에서 5 이상인 값만 선택해 출력

In [199]:
arr = np.random.randint(0,10,15)
ar = arr[::2]
ar1 = ar[ar>=5]
print("짝수 인덱스 값들:",ar)
print("짝수 인덱스 중 5 이상인 값들:",ar1)

짝수 인덱스 값들: [9 5 2 5 2 5 4 4]
짝수 인덱스 중 5 이상인 값들: [9 5 5 5]
